[build]
  base    = "frontend"        # monorepo: run everything from ./frontend
  command = "npm ci && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS    = "--no-fund --no-audit"

# SPA routing (avoid 404s on refresh/deep links)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
