from app import app, db
from models import WeddingDress

dresses = [
    WeddingDress(
        name="Celestial Lace",
        silhouette="A-line",
        shipin48hrs=True,
        neckline="V-neck",
        strapsleevelayout="Straps",
        length="Floor Length",
        collection='Golden Hour',
        fabric="Lace",
        color="Ivory",
        backstyle="Zip-up back",
        price=1500,
        size_range="2-18",
        tags=["elegant", "vintage", "lace"],
        weddingvenue=["beach", "garden"],
        season="spring",
        embellishments=["beading", "embroidery"],
        features=["pockets", "zip-up back", "convertible", "Stay-in-place straps"],
        image_path="1.png"
    ),
    WeddingDress(
        name="Midnight Tulle",
        silhouette="Ballgown",
        shipin48hrs=False,
        neckline="Off-the-Shoulder",
        strapsleevelayout="Straps",
        length="Floor Length",
        collection='Midnight Bloom',
        fabric="Tulle",
        color="Black",
        backstyle="Zipper",
        price=2800,
        size_range="4-22",
        tags=["dramatic", "princess", "twilight"],
        weddingvenue=["ballroom", "cathedral"],
        season="winter",
        embellishments=["sequins", "beading"],
        features=["removable train", "built-in bra"],
        image_path="2.png"
    ),
    WeddingDress(
        name="Satin Whisper",
        silhouette="Sheath",
        shipin48hrs=True,
        neckline="Straight Across",
        strapsleevelayout="Straps",
        length="Chapel Train",
        collection='Modern Muse',
        fabric="Satin",
        color="White",
        backstyle="Keyhole Back",
        price=1200,
        size_range="0-12",
        tags=["minimal", "modern", "sleek"],
        weddingvenue=["rooftop", "courthouse"],
        season="summer",
        embellishments=["none"],
        features=["4-way stretch", "adjustable straps"],
        image_path="3.png"
    ),
    WeddingDress(
        name="Garden Muse",
        silhouette="Fit-and-Flare",
        shipin48hrs=False,
        neckline="V-neck",
        strapsleevelayout="Bell",
        length="Floor Length",
        collection='Botanical Romance',
        fabric="Chiffon",
        color="Blush",
        backstyle="Illusion Back",
        price=1750,
        size_range="6-16",
        tags=["boho", "romantic", "whimsical"],
        weddingvenue=["garden", "vineyard"],
        season="spring",
        embellishments=["floral appliqué", "lace"],
        features=["eco-friendly fabric", "lightweight"],
        image_path="4.png"
    ),
    WeddingDress(
        name="Moonlight Veil",
        silhouette="Mermaid",
        shipin48hrs=True,
        neckline="V-neck",
        strapsleevelayout="Straps",
        length="Chapel Train",
        collection='Moonlight Collection',
        fabric="Organza",
        color="Ivory",
        backstyle="Corset Back",
        price=3200,
        size_range="2-14",
        tags=["glamorous", "bold", "curve-hugging"],
        weddingvenue=["hotel", "evening"],
        season="fall",
        embellishments=["pearls", "crystals"],
        features=["corset back", "sweeping train", "shimmer finish"],
        image_path="5.png"
    ),
    WeddingDress(
        name="Golden Hour",
        silhouette="A-line",
        shipin48hrs=False,
        neckline="Sweetheart",
        strapsleevelayout="Strapless",
        length="Floor Length",
        collection='Golden Hour',
        fabric="Tulle",
        color="Champagne",
        backstyle="Lace-Up",
        price=2500,
        size_range="0-20",
        tags=["romantic", "dreamy", "soft"],
        weddingvenue=["garden", "terrace"],
        season="summer",
        embellishments=["glitter tulle", "lace overlay"],
        features=["pockets", "convertible straps", "lightweight skirt"],
        image_path="6.png"
    ),
    WeddingDress(
        name="Whispering Rose",
        silhouette="Ballgown",
        shipin48hrs=True,
        neckline="Sweetheart",
        strapsleevelayout="Cap Sleeves",
        length="Cathedral Train",
        collection='Rose Reverie',
        fabric="Lace",
        color="Blush",
        backstyle="Zipper + Buttons",
        price=3100,
        size_range="4-18",
        tags=["romantic", "floral", "classic"],
        weddingvenue=["garden", "chapel"],
        season="spring",
        embellishments=["floral embroidery", "beading"],
        features=["illusion neckline", "full skirt", "pockets"],
        image_path="7.png"
    ),
    WeddingDress(
        name="Ocean Pearl",
        silhouette="Sheath",
        shipin48hrs=False,
        neckline="Straight Across",
        strapsleevelayout="Straps",
        length="Knee Length",
        collection='Seaside Glow',
        fabric="Satin",
        color="White",
        backstyle="Low Back",
        price=1100,
        size_range="2-10",
        tags=["simple", "beach", "classic"],
        weddingvenue=["beach", "cruise"],
        season="summer",
        embellishments=["pearls", "subtle beading"],
        features=["built-in support", "anti-wrinkle fabric"],
        image_path="8.png"
    ),
    WeddingDress(
        name="Crystal Breeze",
        silhouette="A-line",
        shipin48hrs=True,
        neckline="Off-the-Shoulder",
        strapsleevelayout="Strapless",
        length="Chapel Train",
        collection='Crystal Dream',
        fabric="Organza",
        color="Ivory",
        backstyle="Corset Back",
        price=1400,
        size_range="6-16",
        tags=["whimsical", "airy", "light"],
        weddingvenue=["mountain", "outdoor"],
        season="fall",
        embellishments=["shimmer organza", "anti-wrinkle"],
        features=["corset back", "airy layers", "easy bustle", "pockets"],
        image_path="9.png"
    ),
    WeddingDress(
        name="Twilight Mist",
        silhouette="Fit-and-Flare",
        shipin48hrs=False,
        neckline="High Neck",
        strapsleevelayout="Shoulder",
        length="Sweep Train",
        collection='Twilight Muse',
        fabric="Chiffon",
        color="White",
        backstyle="Illusion Back",
        price=2700,
        size_range="0-14",
        tags=["modern", "elegant", "refined"],
        weddingvenue=["indoor", "loft"],
        season="winter",
        embellishments=["lace", "beading"],
        features=["illusion neckline", "fitted bodice", "comfortable lining"],
        image_path="10.png"
    ),
]

with app.app_context():
    db.drop_all()
    db.create_all()
    db.session.bulk_save_objects(dresses)
    db.session.commit()
    print("🌸 Dresses added to the collection!")
